[build]
base = "login-system"
publish = "login-system/build"
command = "npm install && npm run build"

[build.environment]
NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200